In [6]:
# !pip install --upgrade pip --user

In [5]:
# !pip install pandas_datareader
# !pip install yfinance

In [4]:
from pandas_datareader import data as pdr
from datetime import date
import yfinance as yf
yf.pdr_override()
import pandas as pd

In [5]:

# Tickers list
# We can add and delete any ticker from the list to get desired ticker live data
ticker_list=['ADANIPORTS.BO','SBIN.BO','RELIANCE.NS','TCS.BO','ASIANPAINT.NS','LICI.BO','BAJFINANCE.NS','WIPRO.BO','AXISBANK.NS','TATAMOTORS.NS','BPCL.NS','COALINDIA.NS','HINDUNILVR.NS','HINDPETRO.NS','DLF.NS','BAJFINANCE.NS','HAVELLS.NS','GODFRYPHLP.NS','EICHERMOT.NS','CIPLA.NS','AMBUJACEM.NS','BPCL.NS','MPHASIS.NS','JSWENERGY.NS','MUTHOOTFIN.NS','CHENNPETRO.NS','BHEL.NS','HAL.NS','DRREDDY.NS','ULTRACEMCO.NS','KOTAKBANK.NS','LT.NS','SUNPHARMA.NS','MARUTI.NS','ADANIGREEN.NS','AWL.NS','ITC.NS','ONGC.NS','BANDHANBNK.NS','PAGEIND.NS','MUTHOOTFIN.NS','BERGEPAINT.NS','MARICO.NS','UPL.NS','SRF.NS']
today = date.today()
# We can get data by our choice by giving days bracket
start_date = '2010-01-01'
end_date = '2020-04-25'
files=[]
def getData(ticker):
    print (ticker)
    data = pdr.get_data_yahoo(ticker, start='2010-01-01'', end='2020-04-25',)
    dataname= ticker #+'_'+str(end_date)
    print(dataname)
    files.append(dataname)
    SaveData(data, dataname)
# Create a data folder in your current dir.
def SaveData(df, filename):
#     for i in ticker_list:
    df.to_csv('data/'+filename+'.csv')
#This loop will iterate over ticker list, will pass one ticker to get data, and save that data as file.
for tik in ticker_list:
    getData(tik)

ADANIPORTS.BO
[*********************100%***********************]  1 of 1 completed
ADANIPORTS.BO
SBIN.BO
[*********************100%***********************]  1 of 1 completed
SBIN.BO
RELIANCE.NS
[*********************100%***********************]  1 of 1 completed
RELIANCE.NS
TCS.BO
[*********************100%***********************]  1 of 1 completed
TCS.BO
ASIANPAINT.NS
[*********************100%***********************]  1 of 1 completed
ASIANPAINT.NS
LICI.BO
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- LICI.BO: No data found for this date range, symbol may be delisted
LICI.BO
BAJFINANCE.NS
[*********************100%***********************]  1 of 1 completed
BAJFINANCE.NS
WIPRO.BO
[*********************100%***********************]  1 of 1 completed
WIPRO.BO
AXISBANK.NS
[*********************100%***********************]  1 of 1 completed
AXISBANK.NS
TATAMOTORS.NS
[*********************100%***********************]  1 of 1 completed
TATAMOTORS.NS
BPCL.NS
[*********************100%***********************]  1 of 1 completed
BPCL.NS
COALINDIA.NS
[*********************100%***********************]  1 of 1 completed
COALINDIA.NS
HINDUNILVR.NS
[*********************100%***********************]  1 of 1 completed
HINDUNILVR.NS
HINDPETRO.NS
[*********************100%***********************]  1 of 1 completed
HINDPETRO.NS
DLF.NS
[*********************100%***********************]  1 of 1 completed
DLF.NS
BAJFINANCE.NS
[*********************100%***********************]  1 of 1 completed
BAJFINANCE.NS
HAVELLS.NS
[*********************100%***********************]  1 of 1 completed
HAVELLS.NS
GODFRYPHLP.NS
[*********************100%***********************]  1 of 1 completed
GODFRYPHLP.NS
EICHERMOT.NS
[*********************100%***********************]  1 of 1 completed
EICHERMOT.NS
CIPLA.NS
[*********************100%***********************]  1 of 1 completed
CIPLA.NS
AMBUJACEM.NS
[*********************100%***********************]  1 of 1 completed
AMBUJACEM.NS
BPCL.NS
[*********************100%***********************]  1 of 1 completed
BPCL.NS
MPHASIS.NS
[*********************100%***********************]  1 of 1 completed
MPHASIS.NS
JSWENERGY.NS
[*********************100%***********************]  1 of 1 completed
JSWENERGY.NS
MUTHOOTFIN.NS
[*********************100%***********************]  1 of 1 completed
MUTHOOTFIN.NS
CHENNPETRO.NS
[*********************100%***********************]  1 of 1 completed
CHENNPETRO.NS
BHEL.NS
[*********************100%***********************]  1 of 1 completed
BHEL.NS
HAL.NS
[*********************100%***********************]  1 of 1 completed
HAL.NS
DRREDDY.NS
[*********************100%***********************]  1 of 1 completed
DRREDDY.NS
ULTRACEMCO.NS
[*********************100%***********************]  1 of 1 completed
ULTRACEMCO.NS
KOTAKBANK.NS
[*********************100%***********************]  1 of 1 completed
KOTAKBANK.NS
LT.NS
[*********************100%***********************]  1 of 1 completed
LT.NS
SUNPHARMA.NS
[*********************100%***********************]  1 of 1 completed
SUNPHARMA.NS
MARUTI.NS
[*********************100%***********************]  1 of 1 completed
MARUTI.NS
ADANIGREEN.NS
[*********************100%***********************]  1 of 1 completed
ADANIGREEN.NS
AWL.NS
[*********************100%***********************]  1 of 1 completed
AWL.NS
ITC.NS
[*********************100%***********************]  1 of 1 completed
ITC.NS
ONGC.NS
[*********************100%***********************]  1 of 1 completed
ONGC.NS
BANDHANBNK.NS
[*********************100%***********************]  1 of 1 completed
BANDHANBNK.NS
PAGEIND.NS
[*********************100%***********************]  1 of 1 completed
PAGEIND.NS
MUTHOOTFIN.NS
[*********************100%***********************]  1 of 1 completed
MUTHOOTFIN.NS
BERGEPAINT.NS
[*********************100%***********************]  1 of 1 completed
BERGEPAINT.NS
MARICO.NS
[*********************100%***********************]  1 of 1 completed
MARICO.NS
UPL.NS
[*********************100%***********************]  1 of 1 completed
UPL.NS
SRF.NS
[*********************100%***********************]  1 of 1 completed
SRF.NS

In [6]:
dff1 = pd.DataFrame(list(zip(ticker_list,ticker_list,ticker_list)), columns=["Symbol","Name","Sector"])
dff1

           Symbol           Name         Sector
0   ADANIPORTS.BO  ADANIPORTS.BO  ADANIPORTS.BO
1         SBIN.BO        SBIN.BO        SBIN.BO
2     RELIANCE.NS    RELIANCE.NS    RELIANCE.NS
3          TCS.BO         TCS.BO         TCS.BO
4   ASIANPAINT.NS  ASIANPAINT.NS  ASIANPAINT.NS
5         LICI.BO        LICI.BO        LICI.BO
6   BAJFINANCE.NS  BAJFINANCE.NS  BAJFINANCE.NS
7        WIPRO.BO       WIPRO.BO       WIPRO.BO
8     AXISBANK.NS    AXISBANK.NS    AXISBANK.NS
9   TATAMOTORS.NS  TATAMOTORS.NS  TATAMOTORS.NS
10        BPCL.NS        BPCL.NS        BPCL.NS
11   COALINDIA.NS   COALINDIA.NS   COALINDIA.NS
12  HINDUNILVR.NS  HINDUNILVR.NS  HINDUNILVR.NS
13   HINDPETRO.NS   HINDPETRO.NS   HINDPETRO.NS
14         DLF.NS         DLF.NS         DLF.NS
15  BAJFINANCE.NS  BAJFINANCE.NS  BAJFINANCE.NS
16     HAVELLS.NS     HAVELLS.NS     HAVELLS.NS
17  GODFRYPHLP.NS  GODFRYPHLP.NS  GODFRYPHLP.NS
18   EICHERMOT.NS   EICHERMOT.NS   EICHERMOT.NS
19       CIPLA.NS       CIPLA.NS       CIPLA.NS
20   AMBUJACEM.NS   AMBUJACEM.NS   AMBUJACEM.NS
21        BPCL.NS        BPCL.NS        BPCL.NS
22     MPHASIS.NS     MPHASIS.NS     MPHASIS.NS
23   JSWENERGY.NS   JSWENERGY.NS   JSWENERGY.NS
24  MUTHOOTFIN.NS  MUTHOOTFIN.NS  MUTHOOTFIN.NS
25  CHENNPETRO.NS  CHENNPETRO.NS  CHENNPETRO.NS
26        BHEL.NS        BHEL.NS        BHEL.NS
27         HAL.NS         HAL.NS         HAL.NS
28     DRREDDY.NS     DRREDDY.NS     DRREDDY.NS
29  ULTRACEMCO.NS  ULTRACEMCO.NS  ULTRACEMCO.NS
30   KOTAKBANK.NS   KOTAKBANK.NS   KOTAKBANK.NS
31          LT.NS          LT.NS          LT.NS
32   SUNPHARMA.NS   SUNPHARMA.NS   SUNPHARMA.NS
33      MARUTI.NS      MARUTI.NS      MARUTI.NS
34  ADANIGREEN.NS  ADANIGREEN.NS  ADANIGREEN.NS
35         AWL.NS         AWL.NS         AWL.NS
36         ITC.NS         ITC.NS         ITC.NS
37        ONGC.NS        ONGC.NS        ONGC.NS
38  BANDHANBNK.NS  BANDHANBNK.NS  BANDHANBNK.NS
39     PAGEIND.NS     PAGEIND.NS     PAGEIND.NS
40  MUTHOOTFIN.NS  MUTHOOTFIN.NS  MUTHOOTFIN.NS
41  BERGEPAINT.NS  BERGEPAINT.NS  BERGEPAINT.NS
42      MARICO.NS      MARICO.NS      MARICO.NS
43         UPL.NS         UPL.NS         UPL.NS
44         SRF.NS         SRF.NS         SRF.NS

In [7]:
df = pd.read_csv("fortune500.csv")
df = pd.concat([df,dff1],axis=0)
df.to_csv("fortune500.csv")

In [6]:
df

           Symbol                 Name                  Sector
0             MMM           3M Company             Industrials
1             AOS      A.O. Smith Corp             Industrials
2             ABT  Abbott Laboratories             Health Care
3            ABBV          AbbVie Inc.             Health Care
4             ACN        Accenture plc  Information Technology
..            ...                  ...                     ...
40  MUTHOOTFIN.NS        MUTHOOTFIN.NS           MUTHOOTFIN.NS
41  BERGEPAINT.NS        BERGEPAINT.NS           BERGEPAINT.NS
42      MARICO.NS            MARICO.NS               MARICO.NS
43         UPL.NS               UPL.NS                  UPL.NS
44         SRF.NS               SRF.NS                  SRF.NS

[532 rows x 3 columns]

In [33]:
import pandas as pd1
df=pd1.read_csv('data//amzn.csv')
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2009-12-31,137.089996,137.279999,134.520004,134.520004,134.520004,4523000
1,2010-01-04,136.250000,136.610001,133.139999,133.899994,133.899994,7599900
2,2010-01-05,133.429993,135.479996,131.809998,134.690002,134.690002,8851900
3,2010-01-06,134.600006,134.729996,131.649994,132.250000,132.250000,7178800
4,2010-01-07,132.009995,132.320007,128.800003,130.000000,130.000000,11030200
...,...,...,...,...,...,...,...
2591,2020-04-20,2389.949951,2444.979980,2386.050049,2393.610107,2393.610107,5770700
2592,2020-04-21,2416.610107,2428.310059,2279.659912,2328.120117,2328.120117,7476700
2593,2020-04-22,2369.000000,2394.000000,2351.000000,2363.489990,2363.489990,4218300
2594,2020-04-23,2399.979980,2424.219971,2382.080078,2399.449951,2399.449951,5066600
2595,2020-04-24,2417.000000,2420.429932,2382.000000,2410.219971,2410.219971,3824900

In [43]:
op=dict(df.loc[10])
for keys in op: 
    op[keys] = str(op[keys])

In [44]:
op

{'Date': '2010-01-15',
 'Open': '129.17999267578122',
 'High': '129.64999389648438',
 'Low': '127.05999755859376',
 'Close': '127.13999938964844',
 'Adj Close': '127.13999938964844',
 'Volume': '15376500'}

In [ ]:
 Getting just the adjusted closing prices. This will return a Pandas DataFrame
# The index in this DataFrame is the major index of the panel_data.
close = panel_data['Close']

# Getting all weekdays between 01/01/2000 and 12/31/2016
all_weekdays = pd.date_range(start=start_date, end=end_date, freq='B')

# How do we align the existing prices in adj_close with our new set of dates?
# All we need to do is reindex close using all_weekdays as the new index
close = close.reindex(all_weekdays)

# Reindexing will insert missing values (NaN) for the dates that were not present
# in the original set. To cope with this, we can fill the missing by replacing them
# with the latest available price for each instrument.
close = close.fillna(method='ffill')
print(all_weekdays)

close.head(10)

close.describe()

# Get the MSFT timeseries. This now returns a Pandas Series object indexed by date.
msft = close.loc[:, 'MSFT']

# Calculate the 20 and 100 days moving averages of the closing prices
short_rolling_msft = msft.rolling(window=20).mean()
long_rolling_msft = msft.rolling(window=100).mean()

# Plot everything by leveraging the very powerful matplotlib package
fig, ax = plt.subplots(figsize=(16,9))

ax.plot(msft.index, msft, label='MSFT')
ax.plot(short_rolling_msft.index, short_rolling_msft, label='20 days rolling')
ax.plot(long_rolling_msft.index, long_rolling_msft, label='100 days rolling')

ax.set_xlabel('Date')
ax.set_ylabel('Adjusted closing price ($)')
ax.legend()

In [3]:
#final fetching price from all


from pandas_datareader import data
import matplotlib.pyplot as plt
import pandas as pd


# We would like all available data from 01/01/2000 until 12/31/2016.
start_date = '2010-01-01'
end_date = '2020-04-25'
df1=pd.read_csv('fortune500.csv')
tickers = list(df1['Symbol'])
print(tickers)
def fetchpriceandsave():
    
# User pandas_reader.data.DataReader to load the desired data. As simple as that.\
    for ik in tickers:
        panel_data = data.DataReader(ik,'yahoo', start_date, end_date)

        #print(panel_data)

        panel_data.to_csv('data//'+ik+'.csv')

fetchpriceandsave()

['MMM', 'AOS', 'ABT', 'ABBV', 'ACN', 'ATVI', 'AYI', 'ADBE', 'AAP', 'AMD', 'AES', 'AET', 'AMG', 'AFL', 'A', 'APD', 'AKAM', 'ALK', 'ALB', 'ARE', 'ALXN', 'ALGN', 'ALLE', 'AGN', 'ADS', 'LNT', 'ALL', 'GOOGL', 'GOOG', 'MO', 'AMZN', 'AEE', 'AAL', 'AEP', 'AXP', 'AIG', 'AMT', 'AWK', 'AMP', 'ABC', 'AME', 'AMGN', 'APH', 'APC', 'ADI', 'ANDV', 'ANSS', 'ANTM', 'AON', 'APA', 'AIV', 'AAPL', 'AMAT', 'APTV', 'ADM', 'ARNC', 'AJG', 'AIZ', 'T', 'ADSK', 'ADP', 'AZO', 'AVB', 'AVY', 'BHGE', 'BLL', 'BAC', 'BAX', 'BBT', 'BDX', 'BRK.B', 'BBY', 'BIIB', 'BLK', 'HRB', 'BA', 'BKNG', 'BWA', 'BXP', 'BSX', 'BHF', 'BMY', 'AVGO', 'BF.B', 'CHRW', 'CA', 'COG', 'CDNS', 'CPB', 'COF', 'CAH', 'KMX', 'CCL', 'CAT', 'CBOE', 'CBRE', 'CBS', 'CELG', 'CNC', 'CNP', 'CTL', 'CERN', 'CF', 'SCHW', 'CHTR', 'CVX', 'CMG', 'CB', 'CHD', 'CI', 'XEC', 'CINF', 'CTAS', 'CSCO', 'C', 'CFG', 'CTXS', 'CME', 'CMS', 'KO', 'CTSH', 'CL', 'CMCSA', 'CMA', 'CAG', 'CXO', 'COP', 'ED', 'STZ', 'GLW', 'COST', 'COTY', 'CCI', 'CSRA', 'CSX', 'CMI', 'CVS', 'DHI', 'DHR', 'DRI', 'DVA', 'DE', 'DAL', 'XRAY', 'DVN', 'DLR', 'DFS', 'DISCA', 'DISCK', 'DISH', 'DG', 'DLTR', 'D', 'DOV', 'DWDP', 'DPS', 'DTE', 'DUK', 'DRE', 'DXC', 'ETFC', 'EMN', 'ETN', 'EBAY', 'ECL', 'EIX', 'EW', 'EA', 'EMR', 'ETR', 'EVHC', 'EOG', 'EQT', 'EFX', 'EQIX', 'EQR', 'ESS', 'EL', 'RE', 'ES', 'EXC', 'EXPE', 'EXPD', 'ESRX', 'EXR', 'XOM', 'FFIV', 'FB', 'FAST', 'FRT', 'FDX', 'FIS', 'FITB', 'FE', 'FISV', 'FLIR', 'FLS', 'FLR', 'FMC', 'FL', 'F', 'FTV', 'FBHS', 'BEN', 'FCX', 'GPS', 'GRMN', 'IT', 'GD', 'GE', 'GGP', 'GIS', 'GM', 'GPC', 'GILD', 'GPN', 'GS', 'GT', 'GWW', 'HAL', 'HBI', 'HOG', 'HRS', 'HIG', 'HAS', 'HCA', 'HCP', 'HP', 'HSIC', 'HES', 'HPE', 'HLT', 'HOLX', 'HD', 'HON', 'HRL', 'HST', 'HPQ', 'HUM', 'HBAN', 'HII', 'IDXX', 'INFO', 'ITW', 'ILMN', 'INCY', 'IR', 'INTC', 'ICE', 'IBM', 'IP', 'IPG', 'IFF', 'INTU', 'ISRG', 'IVZ', 'IPGP', 'IQV', 'IRM', 'JBHT', 'JEC', 'SJM', 'JNJ', 'JCI', 'JPM', 'JNPR', 'KSU', 'K', 'KEY', 'KMB', 'KIM', 'KMI', 'KLAC', 'KSS', 'KHC', 'KR', 'LB', 'LLL', 'LH', 'LRCX', 'LEG', 'LEN', 'LUK', 'LLY', 'LNC', 'LKQ', 'LMT', 'L', 'LOW', 'LYB', 'MTB', 'MAC', 'M', 'MRO', 'MPC', 'MAR', 'MMC', 'MLM', 'MAS', 'MA', 'MAT', 'MKC', 'MCD', 'MCK', 'MDT', 'MRK', 'MET', 'MTD', 'MGM', 'KORS', 'MCHP', 'MU', 'MSFT', 'MAA', 'MHK', 'TAP', 'MDLZ', 'MON', 'MNST', 'MCO', 'MS', 'MSI', 'MYL', 'NDAQ', 'NOV', 'NAVI', 'NKTR', 'NTAP', 'NFLX', 'NWL', 'NFX', 'NEM', 'NWSA', 'NWS', 'NEE', 'NLSN', 'NKE', 'NI', 'NBL', 'JWN', 'NSC', 'NTRS', 'NOC', 'NCLH', 'NRG', 'NUE', 'NVDA', 'ORLY', 'OXY', 'OMC', 'OKE', 'ORCL', 'PCAR', 'PKG', 'PH', 'PAYX', 'PYPL', 'PNR', 'PBCT', 'PEP', 'PKI', 'PRGO', 'PFE', 'PCG', 'PM', 'PSX', 'PNW', 'PXD', 'PNC', 'RL', 'PPG', 'PPL', 'PX', 'PFG', 'PG', 'PGR', 'PLD', 'PRU', 'PEG', 'PSA', 'PHM', 'PVH', 'QRVO', 'QCOM', 'PWR', 'DGX', 'RRC', 'RJF', 'RTN', 'O', 'RHT', 'REG', 'REGN', 'RF', 'RSG', 'RMD', 'RHI', 'ROK', 'COL', 'ROP', 'ROST', 'RCL', 'SPGI', 'CRM', 'SBAC', 'SCG', 'SLB', 'STX', 'SEE', 'SRE', 'SHW', 'SPG', 'SWKS', 'SLG', 'SNA', 'SO', 'LUV', 'SWK', 'SBUX', 'STT', 'SRCL', 'SYK', 'STI', 'SIVB', 'SYMC', 'SYF', 'SNPS', 'SYY', 'TROW', 'TTWO', 'TPR', 'TGT', 'TEL', 'FTI', 'TXN', 'TXT', 'BK', 'CLX', 'COO', 'HSY', 'MOS', 'TRV', 'DIS', 'TMO', 'TIF', 'TWX', 'TJX', 'TMK', 'TSS', 'TSCO', 'TDG', 'TRIP', 'FOXA', 'FOX', 'TSN', 'USB', 'UDR', 'ULTA', 'UAA', 'UA', 'UNP', 'UAL', 'UNH', 'UPS', 'URI', 'UTX', 'UHS', 'UNM', 'VFC', 'VLO', 'VAR', 'VTR', 'VRSN', 'VRSK', 'VZ', 'VRTX', 'VIAB', 'V', 'VNO', 'VMC', 'WMT', 'WBA', 'WM', 'WAT', 'WEC', 'WFC', 'WELL', 'WDC', 'WU', 'WRK', 'WY', 'WHR', 'WMB', 'WLTW', 'WYN', 'WYNN', 'XEL', 'XRX', 'XLNX', 'XL', 'XYL', 'YUM', 'ZBH', 'ZION', 'ZTS']

NotImplementedError: data_source='2010-01-01' is not implemented

In [80]:
### Extract from Yahoo Link ###
import requests
from bs4 import BeautifulSoup
import requests_html
import lxml.html as lh
import pandas as pd
import re
from datetime import datetime
from datetime import timedelta
import time
#import unidecode
ticker_list1=["amzn"]
for ticker in ticker_list1:
    url = 'https://in.finance.yahoo.com/quote/' + ticker
    print(url)
    session = requests_html.HTMLSession()
    r = session.get(url)
    content = BeautifulSoup(r.content, 'html')
    try:
        price = str(content).split('data-reactid="32"')[4].split('</span>')[0].replace('>','')
        #print(str(content).split('data-reactid="47"'))
        openprice = str(content).split('data-reactid="49"')[3].split('</span>')[0].replace('>','')
        rangeobt = str(content).split('data-reactid="67"')[2].split('</span>')[0]
        #price = str(content).split('data-reactid="32"')[4].split('</span>')[0].replace('>','')
        #price = str(content).split('data-reactid="32"')[4].split('</span>')[0].replace('>','')
        #price = str(content).split('data-reactid="32"')[4].split('</span>')[0].replace('>','')
    except IndexError as e:
        price = 0.00
    price = price or "0"
    try:
        price = float(price.replace(',',''))
    except ValueError as e:
        price = 0.00
    time.sleep(1)
   
    print( price)
    print(openprice)
    print(rangeobt)
        #cursor.execute(_SQL, (unidecode.unidecode(ticker[0]), price, unidecode.unidecode(ticker[1]), unidecode.unidecode(ticker[2]), unidecode.unidecode(ticker[3])))
print('completed...')

https://in.finance.yahoo.com/quote/amzn
2410.22
2,417.00
 data-test="FIFTY_TWO_WK_RANGE-value">1,626.03 - 2,461.00</td></tr><tr class="Bxz(bb) Bdbw(1px) Bdbs(s) Bdc($seperatorColor) H(36px)" data-reactid="68"><td class="C($primaryColor) W(51%)" data-reactid="69"><span data-reactid="70">Volume
completed...

In [91]:
import requests
from bs4 import BeautifulSoup
import requests_html
import lxml.html as lh
import pandas as pd
import re
from datetime import datetime
from datetime import timedelta
import time
def fetchcurrentmarketprice(stock):
    stock1=stock
    #for ticker in ticker_list1:
    url = 'https://in.finance.yahoo.com/quote/' + stock1
    print(url)
    session = requests_html.HTMLSession()
    r = session.get(url)
    content = BeautifulSoup(r.content, 'html')
    try:
        price = str(content).split('data-reactid="32"')[4].split('</span>')[0].replace('>','')
        #print(str(content).split('data-reactid="47"'))
        openprice = str(content).split('data-reactid="49"')[3].split('</span>')[0].replace('>','')
        rangeobt = str(content).split('data-reactid="67"')[2].split('</span>')[0]
        #price = str(content).split('data-reactid="32"')[4].split('</span>')[0].replace('>','')
        #price = str(content).split('data-reactid="32"')[4].split('</span>')[0].replace('>','')
        #price = str(content).split('data-reactid="32"')[4].split('</span>')[0].replace('>','')
    except IndexError as e:
        price = 0.00
        price = price or "0"
    try:
        price = float(price.replace(',',''))
    except ValueError as e:
        price = 0.00
        time.sleep(1)
   
    print( price)
    print(openprice)
    print(rangeobt)
        #cursor.execute(_SQL, (unidecode.unidecode(ticker[0]), price, unidecode.unidecode(ticker[1]), unidecode.unidecode(ticker[2]), unidecode.unidecode(ticker[3])))
    return price

In [92]:
fetchcurrentmarketprice('amzn')

https://in.finance.yahoo.com/quote/amzn
2410.22
2,417.00
 data-test="FIFTY_TWO_WK_RANGE-value">1,626.03 - 2,461.00</td></tr><tr class="Bxz(bb) Bdbw(1px) Bdbs(s) Bdc($seperatorColor) H(36px)" data-reactid="68"><td class="C($primaryColor) W(51%)" data-reactid="69"><span data-reactid="70">Volume

2410.22

In [87]:
from lxml import html  
import requests
from time import sleep
import json
import argparse
from collections import OrderedDict
from time import sleep

def parse(ticker):
	url = "http://finance.yahoo.com/quote/%s?p=%s"%(ticker,ticker)
    #print(url)
	response = requests.get(url, verify=False)
	print ("Parsing %s"%(url))
	sleep(4)
	parser = html.fromstring(response.text)
	summary_table = parser.xpath('//div[contains(@data-test,"summary-table")]//tr')
	summary_data = OrderedDict()
	other_details_json_link = "https://query2.finance.yahoo.com/v10/finance/quoteSummary/{0}?formatted=true&lang=en-US&region=US&modules=summaryProfile%2CfinancialData%2CrecommendationTrend%2CupgradeDowngradeHistory%2Cearnings%2CdefaultKeyStatistics%2CcalendarEvents&corsDomain=finance.yahoo.com".format(ticker)
	summary_json_response = requests.get(other_details_json_link)
	try:
		json_loaded_summary =  json.loads(summary_json_response.text)
		y_Target_Est = json_loaded_summary["quoteSummary"]["result"][0]["financialData"]["targetMeanPrice"]['raw']
		earnings_list = json_loaded_summary["quoteSummary"]["result"][0]["calendarEvents"]['earnings']
		eps = json_loaded_summary["quoteSummary"]["result"][0]["defaultKeyStatistics"]["trailingEps"]['raw']
		datelist = []
		for i in earnings_list['earningsDate']:
			datelist.append(i['fmt'])
		earnings_date = ' to '.join(datelist)
		for table_data in summary_table:
			raw_table_key = table_data.xpath('.//td[contains(@class,"C(black)")]//text()')
			raw_table_value = table_data.xpath('.//td[contains(@class,"Ta(end)")]//text()')
			table_key = ''.join(raw_table_key).strip()
			table_value = ''.join(raw_table_value).strip()
			summary_data.update({table_key:table_value})
		summary_data.update({'1y Target Est':y_Target_Est,'EPS (TTM)':eps,'Earnings Date':earnings_date,'ticker':ticker,'url':url})
		return summary_data
	except:
		print ("Failed to parse json response")
		return {"error":"Failed to parse json response"}
		
if __name__=="__main__":

	ticker = "aapl"
	print ("Fetching data for %s"%(ticker))
	scraped_data = parse(ticker)
	print(scraped_data)
	print ("Writing data to output file")
	with open('%s-summary.json'%(ticker),'w') as fp:
		json.dump(scraped_data,fp,indent = 4)

Fetching data for aapl

C:\Users\ADMIN\.conda\envs\project\lib\site-packages\urllib3\connectionpool.py:1004: InsecureRequestWarning: Unverified HTTPS request is being made to host 'finance.yahoo.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,

Parsing http://finance.yahoo.com/quote/aapl?p=aapl
OrderedDict([('', '303.75'), ('1y Target Est', 303.75), ('EPS (TTM)', 12.595), ('Earnings Date', '2020-04-30'), ('ticker', 'aapl'), ('url', 'http://finance.yahoo.com/quote/aapl?p=aapl')])
Writing data to output file

In [89]:
def fetchpriceandsave(val):
    start_date = '2020-04-25'
    end_date = '2020-04-26'    
# User pandas_reader.data.DataReader to load the desired data. As simple as that.\
    #for ik in tickers:
    panel_data = data.DataReader(val, start_date, end_date)

        #print(panel_data)

    panel_data.to_csv(val+'.csv')

fetchpriceandsave('amzn')

[*********************100%***********************]  1 of 1 completed